### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by emilydinan** [atselousov/transformer_chatbot#1]
Thanks for your submission! There may be some delay in evaluation as we have received a large number of submissions in the last couple of days, but I'm writing to confirm that we have received your submission and will be evaluating it. If we have any issues performing the evaluation we will comment here.

**Comment by GolovanovSrg** [comment]
@emilydinan Hi! We provided script to calculate hits metric, but it is not on leaderboard. Is there any problem with our code or you haven't run it yet?

**Comment by emilydinan** [comment]
Hey @GolovanovSrg -- in the process of running, will be posted by the end of the day today.

**Comment by emilydinan** [comment]
In the meantime, we've noticed that your interactive script contains different arguments from the evaluation scripts (like `emoji_prob` and `add_questions`). For MTurk evaluations, we will be evaluating *the exact same* model that was used for the automatic metric evaluations. Can you make edits to your interactive script so that it is the same model? Thanks! (And sorry about the hits@1 delay -- evaluation is still in progress.)

**Comment by GolovanovSrg** [comment]
@emilydinan That parameters add only visual effects. The model is the same. We thought it is allowed, because we did it at hackathon.

**Comment by jaseweston** [comment]
It is not allowed.  These kind of things can game the evaluation versus
other models.
I don't know what was allowed at the hackathon, but it is definitely not
allowed in the competition.

**Comment by atselousov** [comment]
Hey @emilydinan and @jaseweston. Sorry for misunderstanding what the same model means. To resolve this situation we want to clarify some details:
1)  Can we also edit `eval_f1.py` and `eval_hits.py` scripts? 
2)  Can we turn on detokenizer only for interactive mode or it also affects model evaluation results?

**Comment by emilydinan** [comment]
Hi @atselousov,
1. sorry the submission deadline has passed, so we will keep these as is.
2. what do you mean by the detokenizer?

**Comment by atselousov** [comment]
As detokenizer we use MosesDetokenizer + capitalization of first letters in sentences. It must not have any effect on metrics.

**Comment by GolovanovSrg** [comment]
I wanted to write about how you (the organizers) are wrong. But I want to sleep and am very tired from convai (not from development).
