### ISSUE TITLE
Can't find `parameters_names.json` file when fine-tuning from openai's pre-trained model

### ISSUE THREAD

**Issue by linjianz** [atselousov/transformer_chatbot#11]
I want to fine-tune from openai's model, but the file `parameters_names.json` is reqiured, and it is not listed in `https://github.com/openai/finetune-transformer-lm/tree/master/model`. How can I get it?

**Comment by GolovanovSrg** [comment]
Hello. This file: https://github.com/atselousov/transformer_chatbot/blob/agent/parameters_names.json

**Comment by linjianz** [comment]
Thank you so much ^_^

**Comment by shachi04** [comment]
@linjian93 : Were you able to successfully fine-tune on the openai's model? I tried to fine-tune and I only see junk generated! If so, how many epochs did you train for?

**Comment by linjianz** [comment]
@shachi04 I successfully fine-tune on openai's model, but only in other domain (taskbot), and the generated results are reasonable. I trained for about 20+ epochs.
