### ISSUE TITLE
How can I download these .txt files or datasets?

### ISSUE THREAD

**Issue by weizaiff** [atselousov/transformer_chatbot#13]
config's  path of the data:
'train_datasets': ['./datasets/ConvAI2/train_self_revised_no_cands.txt',
                                          './datasets/ConvAI2/train_self_original_no_cands.txt',
                                          './datasets/DailyDialog/train_dailydialog.txt'],
                       'test_datasets': ['./datasets/ConvAI2/valid_self_revised_no_cands.txt',
                                         './datasets/ConvAI2/valid_self_original_no_cands.txt',
                                         './datasets/DailyDialog/valid_dailydialog.txt']

**Comment by GolovanovSrg** [comment]
Hello. Use https://parl.ai/docs/tasks.html

**Comment by weizaiff** [comment]
> Hello. Use https://parl.ai/docs/tasks.html

thx! I'll try it!
