### ISSUE TITLE
How to run as part of ParlAI setup

### ISSUE THREAD

**Issue by jazzminewang** [atselousov/transformer_chatbot#14]
Hi! A team of collaborators at Facebook (Ryan Lowe, Koustuv Sinha) and I are looking at incorporating outputs of your model into a labelled personachat dataset. 

Is it a generative model?

My understanding is that all convai2 submissions were supposed to be structured such that if directly placed in https://github.com/facebookresearch/ParlAI/tree/master/projects/convai2/baselines, I could run eval_f1.py (which is how I've set up the log collection). 

How can I run eval_f1.py on this model without setting up docker?

Fairly urgent - I'm hoping to get this working by tomorrow EOD.

**Comment by jazzminewang** [comment]
Figured out running - is this a retrieval or generative model?

**Comment by jazzminewang** [comment]
Is there any way to make eval_f1.py run faster? The time estimate is ~5 days to collect for the test dataset. Better yet - have you already collected the test logs and train logs somewhere with its responses?

**Comment by jazzminewang** [comment]
For example, is there a flag to use GPU?

**Comment by GolovanovSrg** [comment]
Hi, @jazzminewang. It is a generative model. We didn't have some problems with time with eval_f1.py. eval_f1.py works about few hours on 1080ti. Can i know more about what you plan to do with outputs of the model?

**Comment by GolovanovSrg** [comment]
@jazzminewang do you use gpu?

**Comment by jazzminewang** [comment]
Hi @GolovanovSrg I am running eval_f1.py without setting up the retrieval server (I put the repo in the convai2 baselines folder); would this affect performance?

We are planning to score the outputs with Mturkers and provide that labelled dataset.

Yes, have tried batch size 64/128 - do you have more details exactly on how you ran the script? Do you happen to have the logs from your runs?

**Comment by GolovanovSrg** [comment]
@jazzminewang Retrieval server uses only for fixing some generation problems. We didn't use it in ConvAI2. 
You sure that you are using gpu? Can you show output for `torch.cuda.is_available()`? What hardware do you use?

Why don't you want to use docker?

**Comment by GolovanovSrg** [comment]
For more diversity responses we can change "annealing" parameter.

**Comment by jazzminewang** [comment]
You were right - on the lab machine I was on the cuda install wasn't working properly, have switched machines and it's working much faster now, thanks! 

I do not have docker/sudo access on lab machines, unfortunately.

**Comment by jazzminewang** [comment]
> For more diversity responses we can change "annealing" parameter.

For increased diversity in responses how should these parameters be changed? Do you have suggested values for these?

                        annealing_topk=None,
                        annealing=0,

**Comment by GolovanovSrg** [comment]
@jazzminewang for us good result was with 
```
annealing_topk=None,
annealing=0.6,
```
but we didn't check all possible parameters because we didn't have time.

For understanding these parameters you can look at the code https://github.com/atselousov/transformer_chatbot/blob/e75d2a1eec7209f67f5de21ad7a9598310d3a01e/model/transformer_model.py#L136
