### ISSUE TITLE
Where can I get the dataset for DailyDialogue

### ISSUE THREAD

**Issue by jin8** [atselousov/transformer_chatbot#17]
Hi I have tried downloading the DailyDialogue dataset from parlai. The format seems to not match with the data configuration and dataloader in the code. Is there way to get the dataset other than from parlai? 

Also, your slide (page 3) mentions reddit comments dataset but it is not included in the dataset configuration.  For training, are all three datasets  (convai2, daily dialogue, and reddit comments) needed to achieve the score you stated in the slide (page 10)? 

Thank you,

**Comment by shachi04** [comment]
I downloaded the DailyDialog dataset from http://yanran.li/dailydialog. It has train, test and valid folders. I parsed the "dialogues_train.txt" and others to a format that matches with the dataloader. 

After parsing, my dataset looks something like this: 
Column1 = id (for a 2-turn conversation, restarts at 1 for a new dialog)
Column2 = Utterance by person1
Column3 = Utterance by Person2
___________________________________________________________________________
1	Say , Jim , how about going for a few beers after dinner ? 	 You know that is tempting but is really not good for our fitness . 
2	 What do you mean ? It will help us to relax . 	 Do you really think so ? I don't . It will just make us fat and act silly . Remember last time ? 
3	 I guess you are right.But what shall we do ? I don't feel like sitting at home . 	 I suggest a walk over to the gym where we can play singsong and meet some of our friends . 
4	 That's a good idea . I hear Mary and Sally often go there to play pingpong.Perhaps we can make a foursome with them . 	 Sounds great to me ! If they are willing , we could ask them to go dancing with us.That is excellent exercise and fun , too . 
5	 Good.Let ' s go now . 	 All right . 
1	Can you do push-ups ? 	 Of course I can . It's a piece of cake ! Believe it or not , I can do 30 push-ups a minute . 
2	 Really ? I think that's impossible ! 	 You mean 30 push-ups ? 
3	 Yeah ! 	 It's easy . If you do exercise everyday , you can make it , too . 
___________________________________________________________________________

**Comment by jin8** [comment]
Thank you for replying! I will parse the dataset as you said.
