### ISSUE TITLE
Wild Evaluation begins soon

### ISSUE THREAD

**Issue by madrugado** [atselousov/transformer_chatbot#3]
Dear participants,

We are going to start wild evaluation process soon, so we expect you to make ready your solution for it until Friday, 19th of October. Please make sure that you've tested it with our test server. Please have a look at info about wild evaluation at http://convai.io/wild . It would be helpful if you provide an instruction to run your solution.

If you have any questions/issues we will be glad to help you.

**Comment by atselousov** [comment]
Hey @madrugado. We failed to connect to our bot on test Telegram server (`https://2258.lnsigo.mipt.ru/bot`) with bot token from hackathon (`2f87d974-3808-4fe7-8fee-669541b72c95` You said we can use it). 

Last `convai_world.py` code is used, but we cannot connect to our bot on Telegram:

![screenshot from 2018-10-18 18-40-47](https://user-images.githubusercontent.com/22117239/47166854-c3ea2780-d305-11e8-93f9-9d6365e0f918.png)


`_get_updates` returns `{'ok': True, 'result': []}` with `200` status code.

What do we do wrong?

**Comment by GolovanovSrg** [comment]
@emilydinan @JackUrb  @varvara-l  @klshuster

**Comment by madrugado** [comment]
Seem to be a bug, we'll check this.

**Comment by madrugado** [comment]
Your bot was banned for some reason, please try again.

**Comment by atselousov** [comment]
@madrugado, thank you for your help. We connected to our bot on Telegram test server.

**Comment by GolovanovSrg** [comment]
@madrugado we also updated the code

**Comment by madrugado** [comment]
Thank you, I'll try to get your code running. Is there an instruction to run your solution?

**Comment by atselousov** [comment]
The easiest way to run our code for wild evaluation is to use `Docker` image. You can use prepared bash scripts to create the image and run retrieval server:

1. Run `./environment/prepare_environment.sh` to download model weights, start retrieval server and build `Docker` image.
2. Run `./environment/docker_wild.sh` with console parameters for `wild.py`.
