### ISSUE TITLE
Invitation to present at competition workshop at NIPS

### ISSUE THREAD

**Issue by jaseweston** [atselousov/transformer_chatbot#4]
Hi, as one of the top 7 teams in the automatic evaluations (and you may yet be the winner in human evaluations) we can offer 1 ticket for one of you to attend the NIPS workshops (as we understand you still have to buy the ticket).

We invite you to present at the competition workshop, either with a full talk or a short spotlight + poster, with the length of the talk depending on what happens in the human evaluations (whether you win or not).

What we need from you is:
 (1) let us know you will be coming; and
 (2) the relevant name and  NIPS.CC email address so that we can tell the NIPS organizers to offer a ticket to that address. We need this pretty soon.

Thanks!

**Comment by atselousov** [comment]
Can a person not from team present our solution?

**Comment by jaseweston** [comment]
sure, if you have someone (else) who can present your work clearly, that's fine.

**Comment by atselousov** [comment]
We decided that  Rauf Kurbanov (kurbanov.re@gmail.com) will present our model. He already has a ticket.

**Comment by jaseweston** [comment]
Ok, great thanks.

**Comment by GolovanovSrg** [comment]
@jaseweston Where can we find poster requirements?

**Comment by jaseweston** [comment]
Still to be decided, we are asking NIPS organizers.

**Comment by GolovanovSrg** [comment]
@jaseweston, hi. Is there any news about poster requirements?

**Comment by jaseweston** [comment]
Sorry for the late reply, but we have to work this out with the other
participants.
It looks currently like we do not have enough of the competitors committed
to presenting a poster to make a poster session worthwhile.
You will all be giving talks though. Hope that's ok.
Thanks
Jason

**Comment by GolovanovSrg** [comment]
@jaseweston What is required from us? Only presentation and talk to explain our model?

**Comment by jaseweston** [comment]
Yes

**Comment by emilydinan** [comment]
We have finalized the presentation format for the workshop. Please prepare a presentation (6 minutes talk + 2 minutes questions) which might be expanded (to 8 minutes talk + 4 minutes questions) if you are the winner, so please include all the key ideas in your presentation. We will not have posters. The winner will be announced at NeurIPS.

Thanks and let us know if you have any questions!

**Comment by emilydinan** [comment]
Hi all, 

Could you send your slides to edinan@fb.com and jase@fb.com by 5 PM on Thursday (tomorrow) so we can put them together?

Thanks!
