### ISSUE TITLE
How to train my own model?

### ISSUE THREAD

**Issue by ghostyoona** [atselousov/transformer_chatbot#7]
Hello atselousov:
I want to train my own model with my own data. So I would very appreciate it if you introduce the format of training data and the steps of training process.
Thank you very much!
ghostyoona

**Comment by atselousov** [comment]
Hi @ghostyoona.

Training data has the same format like [parlai](https://github.com/facebookresearch/ParlAI) PersonaChat and DailyDialog datasets. It has to have the format as follow (an example of 2 dialogs):

```
1 your persona: persona info (if any personal info is available)
2 your persona: persona info
3 persona1_replica \t persona2_replica
4 persona1_replica \t persona2_replica

1 your persona: another persona info 
2 your persona: another persona info
3 persona1_replica \t persona2_replica
4 persona1_replica \t persona2_replica
```

You can find the code to parse dataset [here](https://github.com/atselousov/transformer_chatbot/blob/agent/model/dataset.py#L9). 

Settings of training procedure were described in [presentation](https://github.com/atselousov/transformer_chatbot/blob/agent/docs/slides.pdf).

**Comment by ghostyoona** [comment]
@atselousov 
Thanks for your detailed reply! I'll try it out.    👍
