### ISSUE TITLE
How to speak with transformer?

### ISSUE THREAD

**Issue by catruck** [atselousov/transformer_chatbot#8]

**Comment by GolovanovSrg** [comment]
You can use `interactive.py` script. Instructions for starting you can read in the readme.

**Comment by catruck** [comment]
Thanks for answering, 

I have problems with run_retrieval_servet.sh i can't run the server. I need somefing else to instal that not in requirements file? 

P.S. I work on Windows Server 2016

Best regards!

**Comment by GolovanovSrg** [comment]
@atselousov

**Comment by atselousov** [comment]
Hi @catruck.

You need to install `docker` to run the image. Can you specify more information about your problems?

**Comment by catruck** [comment]
Hi @atselousov, 

I installed docker and run prepare_environment.sh, 

- since I work on windows  **sudo** command did't work, i just deleted sudo in all files.
- I have instaled on conda new environment with pytorch.
- I work also local with tensorflow-gpu and all it's works well.
My docker images info:
$ docker images
**REPOSITORY                    TAG                          IMAGE ID            CREATED             SIZE
transformer_chatbot           latest                       e0d9d828bd9e        33 minutes ago      5.77GB
<none>                        <none>                       f277d25badda        About an hour ago   4.37GB
atselousov/retrieval_server   latest                       48e95d0a0fdf        3 months ago        1.24GB
pytorch/pytorch               0.4.1-cuda9-cudnn7-runtime   7b329a33d981        5 months ago        2.91GB**

- When I try to run docker_interactive.sh on docker, I received this error 
**File "interactive.py", line 27, in <module>
    interactive(opt)
  File "/workspace/ParlAI/parlai/scripts/interactive.py", line 54, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/workspace/ParlAI/parlai/core/agents.py", line 462, in create_agent
    model = model_class(opt)
  File "/workspace/agent.py", line 78, in __init__
    self.vocab = BPEVocab.from_files(model_config.bpe_vocab_path, model_config.bpe_codes_path)
  File "/workspace/model/text.py", line 47, in from_files
    with open(vocab_path, 'r', encoding='utf-8') as vocab_file:
FileNotFoundError: [Errno 2] No such file or directory: './parameters/bpe.vocab'**

**all files exist in their locations**

I run file with docker instead nvidia-docker 

P.S. This is my first use of docker

**Comment by atselousov** [comment]
We don’t have any server with Windows, so we didn’t test our scripts on it. It looks like container doesn’t have access to parameters files.

Do you run scripts in the repository root directory (`transformer_chatbot`)?

Does container have access to parameters files? Check it using the following instruction:

1. Run container in interactive mode:

```
sudo nvidia-docker run -it --rm -v $(pwd)/parameters:/workspace/parameters   \
                                -v $(pwd)/checkpoints:/workspace/checkpoints \
                                --network host --entrypoint "/bin/bash" transformer_chatbot
```
It is copy of the code from script `docker_interactive.sh` with different entry point.

2. run inside the container the following bash command:
```
ls -lh ./parameters
```
If the directory is empty try to use absolute path in volume parameter (e.g. instead `-v $(pwd)/checkpoints:/workspace/checkpoints` use `-v /absolute/path/checkpoints:/workspace/checkpoints`)

**Comment by catruck** [comment]
I finally did it.

I  attach file with steps I made on windows env.

[Steps.txt](https://github.com/atselousov/transformer_chatbot/files/2787233/Steps.txt)

Thanks for help!

**Comment by jazzminewang** [comment]
Would it be possible for you to outline the bash commands needed to run this without Docker (say in tmux to keep the server running)? I am running this on a remote server that I don't have sudo access to, so the scripts (run_reirieval_server.sh and create_docker_image.sh) don't work.
